- hosts: localhost
  tasks:
  - name: download maven
    get_url: 
     url: http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
     dest: ~/.
  - name: unzip tar
    unarchive: 
     src: ~/apache-maven-3.3.9-bin.tar.gz
     dest: ~/.
     creates: ~/apache-maven-3.3.9
